-- https://raw.githubusercontent.com/VerbalHubz/Verbal-Hub/main/erm
local Pcall_Result, Pcall_Result_2, Pcall_Result_3, Pcall_Result_4, Pcall_Result_5, MarketplaceService;
local fenv = getfenv();
local success, v35, v36, v37 = pcall(function(a_2, b_2, c_2)
    for for_key_0, for_val_0 in next, fenv do
        local v0 = type(for_key_0);
        local v1 = string.byte(for_key_0, 1, -1);
    end;
    v2, Pcall_Result = pcall(getfenv, 0);
    local v4 = type(Pcall_Result);
    v6, Pcall_Result_2 = pcall(getfenv, 1);
    local v8 = type(Pcall_Result_2);
    v10, Pcall_Result_3 = pcall(getfenv, 2);
    local v12 = type(Pcall_Result_3);
    v14, Pcall_Result_4 = pcall(getfenv, 3);
    local v16 = type(Pcall_Result_4);
    v18, Pcall_Result_5 = pcall(getfenv, 4);
    local v20 = type(Pcall_Result_5);
    local v22, v23 = pcall(setfenv, 0, Pcall_Result);
    local v24, v25 = pcall(setfenv, 1, Pcall_Result_2);
    local v26, v27 = pcall(setfenv, 2, Pcall_Result_3);
    local v28, v29 = pcall(setfenv, 3, Pcall_Result_4);
    local v30, v31 = pcall(setfenv, 4, Pcall_Result_5);
    local v33, v34 = pcall(loadstring, [=[
        --[[

                         .@%(/*,.......      ...,,*/(#%&@@.
                     (*   ,/(#%%&&@@@@&%((////(((##%###((/**,,.     ,//(&.
                   /* .%@@@@@@@@%,  .(&@@@&&&&&&@@@@@@&#(*,........*%@@@(.  ,#.
                 */ .&@@@@@@@*  (%,   *(&&@@@@@&%(*,.             .,*(#%(*@@&*  *,
                #, /@@@@@@* *&( ,&&/.,/#%&&@@@&(&@@@@@@@@@@@@#*,.....,/&@@@@@@@@( .%
               #  #@@@@@*/@% .#%./(,.,/*,//*,.,/(*@@@@@@@@@@@@%@@@@@@@@@#.#@@@@@@&. %
              /  &@@@@@@@@(%@# *&&*&@@@@#/&@@@@/%%.,%@@@@@@@%/@@&(,  ,,,...  *%@@@# *
            #  .&@@@@@@@@@@@,((%@@@@@#.    ,&@@#@@&* .&@@@@@&,.#@@@@/&@@%(@@@&(/,(&, /,
         (/   (@&&&%&@@@&/, ,@#(@@@@,        #@@/,&@& /@@@@@,%#%@@@@@(     *@@@@@&,%%. .
        /  #/,#@@@&#(//#@@@/ %@@@&@@@(.    ,&@@(.*/*  %@@*   %@@@@@@%       (@@&(*...%&.
         ///@@&,  (&@@#,   /@/ ,*&@@@@#&@@%#%((%@&* /@@@@@@&. #@@@#&@@@&%%@@@@@@&,/(*@/#
        %%.&@# .&@@@# /@@@@%&@@@&/.   ,/((/*,  ./&@@@@@@@@@@,*&(./%@@#*&@@@(#(....,&#*@/
        @%.&& .&@@@&*    /&@@@@@@@@@@@@@@@@&@@#/(%@@@@@@@@@@&,  (@@@@@@@@@@@@/,@@@@@#.&*
        &&,%% .&*    /@@@(.  ,(@@@@@&/(////#( /&@@@@@@@@@@@@@@@(  ,&@@@@@@@@&, (@@&*/@(/
        .%*#@( /@@@@( *@@@@@@/     *%@@@@@@@&.,@& ,#, .&@@@@@@# .#*%&/,#@@@@*   *@@&/*&*
         .&/.#@@@@@@@,   *&@@%.,&@@&(,    ,(%@%&@@@@@@@@@(.*,  /@@@@@@@@@&,      %@@@@..
        @* .%@@@@@@@@(       .   (@@@@@@@@(       .*(%&@@@@@@@@@@@@&(,  ./.*@%   /@@% ./
          @* .&@@@@@@&.             ./&@@@*.&@@@@@@@&, ,**,.    .,*(&(.%@@# %@*  ,@@% ,#
            &, /@@@@@@*                    .#@@@@@@@@*.%@@@@@(,@@@@@@& ,%(.      .&@% ,#
              / *@@@@@#                                                           %@&.,#
              (( .&@@@@*                                                          #@&.,#
               .&. ,&@@@,                                                         (@&.,#
                  #. .%@@* /@@/                                                   /@&.,(
                    ./  #@%. %@&,,#,                                              /@@,./
                      *(  #@%. . (@@@@@%/,                                        /@@,.*
                        //  %@&, *@@@@@@@@( (@%/.                                 #@@, (
                          #* .&@@#. (@@@@&.*@@@@@@@@%. */.                  *..%*.&@@, /
                            @* .%@@@%, ,/ .@@@@@@@@@@,.%@@@@@% .&@@@* #@&..&@*,* %@@&. *
                               /  *&@@@@%,   *(&@@@@&. #@@@@@* #@@@% (@@* ,.   /@@@@* (
                                 @#. .#@@@@@@&(,.                      .,*(%&@@@@@&..(
                                     &(.   ./%@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@(. ((
                                          ,#/*.       ..,,,,,,,,....          ,/#

        ]]--

         return setfenv(function(...) return wWWRtB(...) end, setmetatable({ ["wWWRtB"] = ... }, { __index = getfenv((...)) })) ]=], "Luraph");
    return false, 53, 53;
end);
local success_1, v50 = pcall(function(a_3, b_3, c_3)
    getgenv().whscript = "🔗 Verbal Hub MAX PROTECTION";
    getgenv().webhookexecUrl = "https://dcwh.my/post?uniqueid=3b97df8b";
    getgenv().ExecLogSecret = false;
    getgenv().ThumbnailURL = "https://cdn.discordapp.com/icons/985335776109813810/f2030cf5cdd47974e5779c2fab137f3f.png?size=2048";
    getgenv().FooterIconURL = "https://cdn.discordapp.com/icons/985335776109813810/3018ae818c9b2233d92e272fbd54575c.png?size=2048";
    local v38 = game.GetService;
    local v39 = game:GetService("Players");
    local v40 = v39.LocalPlayer;
    local v41 = game.GetService;
    local v42 = game:GetService("Players");
    local _ = v40.UserId;
    local v44 = game.PlaceId;
    local v45 = game.JobId;
    local v46 = game.GetService;
    local v48 = game:GetService("MarketplaceService").GetProductInfo;
    local v49 = game:GetService("MarketplaceService"):GetProductInfo(v44);
end);
